### PR TITLE
Fix build command

### PR DESCRIPTION
**Pull request by zabil**

### CODE REVIEW

**Comment by zabil** [comment]
@BugDiver I think the gh release usage is in the release.yml is wrong. I can take a look at it. It's failed to publish the package because of this line

https://github.com/getgauge/gauge-ts/blob/c7a59a72d34e518e35654020021d66f17d548e28/.github/workflows/release.yml#L56-L59

Which tries to create a new release everytime we call it. I don't see an edit release flag.

**Comment by BugDiver** [comment]
@zabil The latest deployment is done successfully, although the script needs some cleanup and we also need to update the version in `gauge-repository`. I will raise a PR for the same in sometime.

**Comment by zabil** [comment]
Thanks @BugDiver can you also take a look at the template repo. gauge init ts fails as the zip is not packaged on merge. We can upgrade the template to refer to the latest version of gauge.

**Comment by BugDiver** [comment]
@zabil  I have already fixed that, the latest template release has all required assets.

https://github.com/getgauge/template-ts/actions/runs/9416654645/job/25940335811

**Pull request merged**
